#!/usr/bin/env node
// Builds parts.js from assets/parts/*.svg (exported from the Peeple Figma "Generátor" page).
// Each part is a 113x113 frame. We strip the frame background, clip-paths and ids,
// and replace the ink colours with placeholders so they can be swapped at render time.
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', 'assets', 'parts');
const OUT = path.join(__dirname, '..', 'parts.js');

const CATEGORIES = ['eyes', 'mouth', 'beard', 'hat', 'accessory', 'hand'];

// Skin tones, lightest → darkest (from the Figma skin-* tiles).
const TONES = ['#FFFFFF', '#E5E5EA', '#C7C7CC', '#8E8E93', '#3A3A3C', '#1B1D1A'];

function inner(svg) {
  const m = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/);
  if (!m) throw new Error('no <svg> root');
  let s = m[1];
  s = s.replace(/<defs>[\s\S]*?<\/defs>/g, '');
  s = s.replace(/<rect width="113" height="113" fill="[^"]*"\s*\/>/g, '');
  s = s.replace(/\s+clip-path="url\(#[^)]*\)"/g, '');
  s = s.replace(/\s+id="[^"]*"/g, '');
  // ink placeholders
  s = s.replace(/fill="#1B1D1A"/g, 'fill="__INK__"');
  s = s.replace(/fill="black"/g, 'fill="__INK__"');
  s = s.replace(/fill="white"/g, 'fill="__PAPER__"');
  s = s.replace(/fill="#F5F5F5"/g, 'fill="__PAPER__"'); // frame-colour stroke artifacts
  s = s.replace(/\s*\n\s*/g, '');
  // drop now-empty groups
  for (let i = 0; i < 4; i++) s = s.replace(/<g>\s*<\/g>/g, '');
  return s.trim();
}

function numericSort(a, b) {
  return parseInt(a.split('-').pop(), 10) - parseInt(b.split('-').pop(), 10);
}

const files = fs.readdirSync(SRC).filter(f => f.endsWith('.svg'));
const parts = {};
for (const cat of CATEGORIES) {
  const names = files.filter(f => f.startsWith(cat + '-')).map(f => f.replace('.svg', '')).sort(numericSort);
  parts[cat] = names.map(name => ({ id: name, svg: inner(fs.readFileSync(path.join(SRC, name + '.svg'), 'utf8')) }));
}

// Figure (head + body) shared by all skin tones — take it from skin-0 (white figure) and
// replace the figure fill with a placeholder.
let figure = inner(fs.readFileSync(path.join(SRC, 'skin-0.svg'), 'utf8'));
figure = figure.replace(/fill="__PAPER__"/g, 'fill="__SKIN__"');

const out = `// Generated by scripts/build-parts.js — do not edit by hand.
// Source: Figma "Peeple | Generátor" (node 92-134). ${files.length} files.
window.PEEPLE_PARTS = ${JSON.stringify({ tones: TONES, figure, parts }, null, 0)};
`;
fs.writeFileSync(OUT, out);
const counts = Object.fromEntries(Object.entries(parts).map(([k, v]) => [k, v.length]));
console.log('wrote', OUT, (out.length / 1024).toFixed(1) + 'KB', counts);
